import { Word } from '../types';

export const DEFAULT_ELEMENTARY_WORDS: Omit<Word, 'id' | 'createdAt'>[] = [
  // 1. 맞춤법 필수 (초등 3~4학년 혼동 어휘)
  { text: '어떡해', category: '맞춤법', difficulty: 'easy', hint: "'어떻게 해'가 줄어든 말이에요." },
  { text: '어떻게', category: '맞춤법', difficulty: 'easy', hint: "'어떠하게'의 줄임말로 방법을 물을 때 써요." },
  { text: '왠지', category: '맞춤법', difficulty: 'easy', hint: "'왜인지'의 줄임말로 이유를 모를 때 써요." },
  { text: '웬일이야', category: '맞춤법', difficulty: 'normal', hint: "'어찌 된 일'을 뜻할 때는 '웬'을 써요." },
  { text: '깨끗이', category: '맞춤법', difficulty: 'easy', hint: "'깨끗하다'에서 온 부사는 '-이'로 적어요." },
  { text: '곰곰이', category: '맞춤법', difficulty: 'easy', hint: "'곰곰이 생각하다'처럼 '-이'로 적어요." },
  { text: '일찍이', category: '맞춤법', difficulty: 'easy', hint: "'일찍'에 '-이'가 붙은 말이에요." },
  { text: '반드시', category: '맞춤법', difficulty: 'normal', hint: "'틀림없이 꼭'이라는 뜻이에요." },
  { text: '반듯이', category: '맞춤법', difficulty: 'normal', hint: "'삐뚤어지지 않고 바르게'라는 뜻이에요." },
  { text: '가르치다', category: '맞춤법', difficulty: 'normal', hint: "지식이나 배움을 알려줄 때 써요." },
  { text: '가리키다', category: '맞춤법', difficulty: 'normal', hint: "손가락 등으로 방향을 짚을 때 써요." },
  { text: '설거지', category: '맞춤법', difficulty: 'easy', hint: "'설겆이'가 아니라 소리 나는 대로 '설거지'예요." },
  { text: '바람개비', category: '맞춤법', difficulty: 'easy', hint: "바람을 받으면 뱅글뱅글 도는 장난감이에요." },
  { text: '오뚝이', category: '맞춤법', difficulty: 'easy', hint: "넘어져도 다시 일어나는 인형이에요." },
  { text: '부치다', category: '맞춤법', difficulty: 'normal', hint: "편지를 보내거나 부침개를 지질 때 써요." },
  { text: '붙이다', category: '맞춤법', difficulty: 'normal', hint: "풀이나 테이프로 찰싹 닿게 할 때 써요." },
  { text: '너머', category: '맞춤법', difficulty: 'normal', hint: "산이나 담 '너머'처럼 높거나 가린 것의 저쪽을 뜻해요." },
  { text: '안간힘', category: '맞춤법', difficulty: 'hard', hint: "'앙간힘'이 아니라 '안간힘'을 쓰다예요." },
  { text: '핼쑥하다', category: '맞춤법', difficulty: 'hard', hint: "얼굴에 핏기가 없고 파리할 때 써요." },
  { text: '금세', category: '맞춤법', difficulty: 'normal', hint: "'금시에'가 줄어든 말로 '금새'가 아니에요." },
  { text: '넓적하다', category: '맞춤법', difficulty: 'hard', hint: "'널찍하다'와 구분하여 받침 'ㄼ'을 써요." },
  { text: '희한하다', category: '맞춤법', difficulty: 'normal', hint: "'희안하다'가 아니라 '희한하다'예요." },
  { text: '설렘', category: '맞춤법', difficulty: 'normal', hint: "'설레임'이 아니라 '설렘'이 맞아요." },
  { text: '며칠 동안', category: '맞춤법', difficulty: 'normal', hint: "'몇 일'이 아니라 언제나 '며칠'로 적어요." },

  // 2. 띄어쓰기 (조사, 의존명사, 단위명사)
  { text: '할 수 있다', category: '띄어쓰기', difficulty: 'easy', hint: "'수'는 의존명사이므로 앞말과 띄어 써요." },
  { text: '보고 싶다', category: '띄어쓰기', difficulty: 'easy', hint: "본용언과 보조용언은 띄어 쓰는 것이 원칙이에요." },
  { text: '사과 한 개', category: '띄어쓰기', difficulty: 'easy', hint: "수를 나타내는 말과 단위를 나타내는 명사는 띄어 써요." },
  { text: '책 두 권', category: '띄어쓰기', difficulty: 'easy', hint: "'두'와 '권'을 띄어 써요." },
  { text: '갈 것 같다', category: '띄어쓰기', difficulty: 'normal', hint: "'것'은 의존명사이므로 띄어 써요." },
  { text: '학교에 가다', category: '띄어쓰기', difficulty: 'easy', hint: "'에'는 조사이므로 앞말에 붙여 써요." },
  { text: '비가 올 때', category: '띄어쓰기', difficulty: 'normal', hint: "'올'과 '때'를 띄어 써요." },
  { text: '너만큼 좋아해', category: '띄어쓰기', difficulty: 'normal', hint: "체언 뒤에 붙는 '만큼'은 조사라 붙여 써요." },
  { text: '노력한 만큼', category: '띄어쓰기', difficulty: 'hard', hint: "용언 어간 뒤의 '만큼'은 의존명사라 띄어 써요." },
  { text: '밥을 먹은 후', category: '띄어쓰기', difficulty: 'normal', hint: "'후'는 명사이므로 앞말과 띄어 써요." },
  { text: '친구와 함께', category: '띄어쓰기', difficulty: 'easy', hint: "'함께'는 부사이므로 앞말과 띄어 써요." },
  { text: '공부를 열심히', category: '띄어쓰기', difficulty: 'easy', hint: "'열심히'는 부사이므로 띄어 써요." },
  { text: '열 살 어린이', category: '띄어쓰기', difficulty: 'normal', hint: "'열'과 '살'과 '어린이'를 모두 띄어 써요." },
  { text: '집에 가는 길', category: '띄어쓰기', difficulty: 'normal', hint: "'가는'과 '길'을 띄어 써요." },
  { text: '아는 척하다', category: '띄어쓰기', difficulty: 'hard', hint: "'척하다'는 보조용언이에요." },

  // 3. 교과서 속담 및 명언 (3~4학년 교과서)
  { text: '시작이 반이다', category: '속담', difficulty: 'easy', hint: "무슨 일이든 시작하기만 하면 이미 절반은 한 셈이에요." },
  { text: '티끌 모아 태산', category: '속담', difficulty: 'easy', hint: "아무리 작은 것도 모이면 큰 것이 돼요." },
  { text: '등잔 밑이 어둡다', category: '속담', difficulty: 'normal', hint: "가까이 있는 것을 오히려 더 모를 수 있어요." },
  { text: '고래 싸움에 새우 등 터진다', category: '속담', difficulty: 'hard', hint: "강한 자들의 싸움에 약한 자가 피해를 입어요." },
  { text: '백지장도 맞들면 낫다', category: '속담', difficulty: 'normal', hint: "쉬운 일이라도 서로 힘을 합치면 훨씬 쉬워요." },
  { text: '가는 말이 고와야 오는 말이 곱다', category: '속담', difficulty: 'hard', hint: "내가 남에게 말을 좋게 해야 남도 내게 곱게 말해요." },
  { text: '발 없는 말이 천 리 간다', category: '속담', difficulty: 'normal', hint: "말은 순식간에 멀리 퍼지니 늘 조심해야 해요." },
  { text: '소 잃고 외양간 고친다', category: '속담', difficulty: 'normal', hint: "이미 일을 그르친 뒤에는 후회해도 소용이 없어요." },
  { text: '우물 안 개구리', category: '속담', difficulty: 'easy', hint: "견문이 좁아 세상 넓은 줄 모르는 사람을 뜻해요." },
  { text: '원숭이도 나무에서 떨어진다', category: '속담', difficulty: 'normal', hint: "아무리 익숙하고 잘하는 사람도 실수할 때가 있어요." },
  { text: '돌다리도 두들겨 보고 건너라', category: '속담', difficulty: 'hard', hint: "잘 아는 일이라도 매사 신중하게 해야 해요." },
];
